let products=[];let cart=[];let activeCategory='Todos';
const $=s=>document.querySelector(s);const money=v=>Number(v).toLocaleString('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0});

async function loadProducts(){try{const r=await fetch('/api/products');if(!r.ok)throw new Error();products=await r.json();renderFilters();renderProducts();}catch(e){$('#products').innerHTML='<p class="loading">No se pudieron cargar los productos. Inicia el backend con <b>npm start</b>.</p>';}}
function renderFilters(){const cats=['Todos',...new Set(products.map(p=>p.category))];$('#filters').innerHTML=cats.map(c=>`<button type="button" class="filter ${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.cat;renderFilters();renderProducts()}));}
function renderProducts(){const list=activeCategory==='Todos'?products:products.filter(p=>p.category===activeCategory);$('#products').innerHTML=list.map(p=>`<article class="card"><img class="card-img" src="${p.img}" alt="${p.name}"><div class="card-content"><span class="category">${p.category}</span><h3>${p.name}</h3><p class="desc">${p.description}</p><p class="price">${money(p.price)}</p><button class="add-btn" type="button" data-add="${p.id}">Agregar al carrito</button></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(Number(b.dataset.add))));}
function addToCart(id){const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({...products.find(p=>p.id===id),qty:1});renderCart();openCart();}
function changeQty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);renderCart();}
function removeItem(id){cart=cart.filter(i=>i.id!==id);renderCart();}
function totals(){const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);const shipping=subtotal>=1500000||subtotal===0?0:25000;return{subtotal,shipping,total:subtotal+shipping}}
function renderCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;$('#cartSubtitle').textContent=`${count} ${count===1?'producto':'productos'}`;const box=$('#cartItems');if(!cart.length){box.innerHTML='<div class="empty">🛒<p>Tu carrito está vacío.</p></div>';}else{box.innerHTML=cart.map(x=>`<div class="drawer-item"><img src="${x.img}" alt="${x.name}"><div><div class="drawer-name">${x.name}</div><div class="drawer-price">${money(x.price)}</div><div class="drawer-controls"><div class="qty"><button type="button" data-q="-1" data-id="${x.id}">−</button><span>${x.qty}</span><button type="button" data-q="1" data-id="${x.id}">+</button></div><button type="button" class="remove" data-remove="${x.id}">Eliminar</button></div></div></div>`).join('');document.querySelectorAll('[data-q]').forEach(b=>b.addEventListener('click',()=>changeQty(Number(b.dataset.id),Number(b.dataset.q))));document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>removeItem(Number(b.dataset.remove))));}const t=totals();$('#subtotal').textContent=money(t.subtotal);$('#shipping').textContent=t.shipping?'$25.000':'GRATIS';$('#drawerTotal').textContent=money(t.total);$('#goCheckout').disabled=!cart.length;$('#goCheckout').style.opacity=cart.length?1:.5;}
function openCart(){$('#cartOverlay').classList.add('open');document.body.classList.add('lock')}function closeCart(){$('#cartOverlay').classList.remove('open');document.body.classList.remove('lock')}
function openPurchase(){if(!cart.length){alert('Primero agrega una consola al carrito.');return}$('#purchaseTotal').textContent=money(totals().total);$('#purchaseOverlay').classList.add('open');document.body.classList.add('lock')}
function closePurchase(){$('#purchaseOverlay').classList.remove('open');document.body.classList.remove('lock')}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}

$('#openCart').addEventListener('click',openCart);$('#heroCart').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#cartOverlay').addEventListener('click',e=>{if(e.target.id==='cartOverlay')closeCart()});$('#goCheckout').addEventListener('click',()=>{closeCart();openPurchase()});$('#closePurchase').addEventListener('click',closePurchase);$('#purchaseOverlay').addEventListener('click',e=>{if(e.target.id==='purchaseOverlay')closePurchase()});

document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closePurchase()}});
$('#checkoutForm').addEventListener('submit',async e=>{e.preventDefault();if(!cart.length)return;const customer={name:$('#name').value.trim(),phone:$('#phone').value.trim(),email:$('#email').value.trim(),address:$('#address').value.trim(),city:$('#city').value.trim()};const payload={customer,payment:$('#payment').value,items:cart.map(x=>({id:x.id,qty:x.qty}))};try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.message||'No se pudo registrar el pedido');const name=customer.name;cart=[];renderCart();closePurchase();e.target.reset();alert(`¡Gracias por tu compra, ${name}! 🎮\n\nTu pedido fue registrado correctamente.\nNúmero de pedido: ${data.order.id}`);showToast('Pedido registrado correctamente');}catch(err){alert('No se pudo registrar el pedido. Verifica que el backend esté encendido.')}});

loadProducts();renderCart();
